for /r %%a in (Barbarian.rushee.js) do (
    copy "%%a" "%%a.TMPA1"
    ren "%%a.TMPA1" "Barbarian.accaga.js"
    copy "%%a" "%%a.TMPA2"
    ren "%%a.TMPA2" "Barbarian.accagb.js"
    copy "%%a" "%%a.TMPA3"
    ren "%%a.TMPA3" "Barbarian.accagc.js"
    copy "%%a" "%%a.TMPA4"
    ren "%%a.TMPA4" "Barbarian.accagd.js"
    copy "%%a" "%%a.TMPA5"
    ren "%%a.TMPA5" "Barbarian.accage.js"
    copy "%%a" "%%a.TMPA6"
    ren "%%a.TMPA6" "Barbarian.accagf.js"
    copy "%%a" "%%a.TMPA7"
    ren "%%a.TMPA7" "Barbarian.accagg.js"
    copy "%%a" "%%a.TMPA8"
    ren "%%a.TMPA8" "Barbarian.accagh.js"
)
for /r %%a in (Barbarian.rushee.js) do (
    copy "%%a" "%%a.TMPA1"
    ren "%%a.TMPA1" "Barbarian.accafa.js"
    copy "%%a" "%%a.TMPA2"
    ren "%%a.TMPA2" "Barbarian.accafb.js"
    copy "%%a" "%%a.TMPA3"
    ren "%%a.TMPA3" "Barbarian.accafc.js"
    copy "%%a" "%%a.TMPA4"
    ren "%%a.TMPA4" "Barbarian.accafd.js"
    copy "%%a" "%%a.TMPA5"
    ren "%%a.TMPA5" "Barbarian.accafe.js"
    copy "%%a" "%%a.TMPA6"
    ren "%%a.TMPA6" "Barbarian.accaff.js"
    copy "%%a" "%%a.TMPA7"
    ren "%%a.TMPA7" "Barbarian.accafg.js"
    copy "%%a" "%%a.TMPA8"
    ren "%%a.TMPA8" "Barbarian.accafh.js"
)
for /r %%a in (Barbarian.rushee.js) do (
    copy "%%a" "%%a.TMPA1"
    ren "%%a.TMPA1" "Barbarian.accaea.js"
    copy "%%a" "%%a.TMPA2"
    ren "%%a.TMPA2" "Barbarian.accaeb.js"
    copy "%%a" "%%a.TMPA3"
    ren "%%a.TMPA3" "Barbarian.accaec.js"
    copy "%%a" "%%a.TMPA4"
    ren "%%a.TMPA4" "Barbarian.accaed.js"
    copy "%%a" "%%a.TMPA5"
    ren "%%a.TMPA5" "Barbarian.accaee.js"
    copy "%%a" "%%a.TMPA6"
    ren "%%a.TMPA6" "Barbarian.accaef.js"
    copy "%%a" "%%a.TMPA7"
    ren "%%a.TMPA7" "Barbarian.accaeg.js"
    copy "%%a" "%%a.TMPA8"
    ren "%%a.TMPA8" "Barbarian.accaeh.js"
)
for /r %%a in (Barbarian.rushee.js) do (
    copy "%%a" "%%a.TMPA1"
    ren "%%a.TMPA1" "Barbarian.accada.js"
    copy "%%a" "%%a.TMPA2"
    ren "%%a.TMPA2" "Barbarian.accadb.js"
    copy "%%a" "%%a.TMPA3"
    ren "%%a.TMPA3" "Barbarian.accadc.js"
    copy "%%a" "%%a.TMPA4"
    ren "%%a.TMPA4" "Barbarian.accadd.js"
    copy "%%a" "%%a.TMPA5"
    ren "%%a.TMPA5" "Barbarian.accade.js"
    copy "%%a" "%%a.TMPA6"
    ren "%%a.TMPA6" "Barbarian.accadf.js"
    copy "%%a" "%%a.TMPA7"
    ren "%%a.TMPA7" "Barbarian.accadg.js"
    copy "%%a" "%%a.TMPA8"
    ren "%%a.TMPA8" "Barbarian.accadh.js"
)
for /r %%a in (Barbarian.rushee.js) do (
    copy "%%a" "%%a.TMPA1"
    ren "%%a.TMPA1" "Barbarian.accaca.js"
    copy "%%a" "%%a.TMPA2"
    ren "%%a.TMPA2" "Barbarian.accacb.js"
    copy "%%a" "%%a.TMPA3"
    ren "%%a.TMPA3" "Barbarian.accacc.js"
    copy "%%a" "%%a.TMPA4"
    ren "%%a.TMPA4" "Barbarian.accacd.js"
    copy "%%a" "%%a.TMPA5"
    ren "%%a.TMPA5" "Barbarian.accace.js"
    copy "%%a" "%%a.TMPA6"
    ren "%%a.TMPA6" "Barbarian.accacf.js"
    copy "%%a" "%%a.TMPA7"
    ren "%%a.TMPA7" "Barbarian.accacg.js"
    copy "%%a" "%%a.TMPA8"
    ren "%%a.TMPA8" "Barbarian.accach.js"
)
for /r %%a in (Barbarian.rushee.js) do (
    copy "%%a" "%%a.TMPA1"
    ren "%%a.TMPA1" "Barbarian.accaba.js"
    copy "%%a" "%%a.TMPA2"
    ren "%%a.TMPA2" "Barbarian.accabb.js"
    copy "%%a" "%%a.TMPA3"
    ren "%%a.TMPA3" "Barbarian.accabc.js"
    copy "%%a" "%%a.TMPA4"
    ren "%%a.TMPA4" "Barbarian.accabd.js"
    copy "%%a" "%%a.TMPA5"
    ren "%%a.TMPA5" "Barbarian.accabe.js"
    copy "%%a" "%%a.TMPA6"
    ren "%%a.TMPA6" "Barbarian.accabf.js"
    copy "%%a" "%%a.TMPA7"
    ren "%%a.TMPA7" "Barbarian.accabg.js"
    copy "%%a" "%%a.TMPA8"
    ren "%%a.TMPA8" "Barbarian.accabh.js"
)
for /r %%a in (Barbarian.rushee.js) do (
    copy "%%a" "%%a.TMPA1"
    ren "%%a.TMPA1" "Barbarian.accaaa.js"
    copy "%%a" "%%a.TMPA2"
    ren "%%a.TMPA2" "Barbarian.accaab.js"
    copy "%%a" "%%a.TMPA3"
    ren "%%a.TMPA3" "Barbarian.accaac.js"
    copy "%%a" "%%a.TMPA4"
    ren "%%a.TMPA4" "Barbarian.accaad.js"
    copy "%%a" "%%a.TMPA5"
    ren "%%a.TMPA5" "Barbarian.accaae.js"
    copy "%%a" "%%a.TMPA6"
    ren "%%a.TMPA6" "Barbarian.accaaf.js"
    copy "%%a" "%%a.TMPA7"
    ren "%%a.TMPA7" "Barbarian.accaag.js"
    copy "%%a" "%%a.TMPA8"
    ren "%%a.TMPA8" "Barbarian.accaah.js"
)